source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'Alamofire', '~> 4.0'
pod 'URITemplate'
pod 'SwiftyJSON'

target 'SwiftyTraverson_Example' do
  pod 'SwiftyTraverson', :path => "../"
end

target 'SwiftyTraverson_Tests' do
  pod 'SwiftyTraverson', :path => "../"
  
  pod 'OHHTTPStubs'
  pod 'OHHTTPStubs/Swift'
end
